name: flutter_cbl_learning_path
description: Learning Path for Couchbase Lite and Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  archive: ^3.3.5
  bloc: ^8.1.0
  cbl_flutter_ce: ^2.1.2
  cbl_flutter: ^2.0.2
  cbl: ^2.1.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: 1.5.1
  formz: ^0.4.1
  google_fonts: ^3.0.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  path: ^1.8.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  cbl_dart: ^2.1.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - asset/images/couchbase.png
    - asset/database/startingWarehouses.zip
